apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-pv-volume
  namespace: demo
  labels:
    type: local
spec:
  storageClassName: demo
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/pvc/demo"
